import Link from "next/link";
import mongoose from "mongoose";
import { notFound } from "next/navigation";
import { connectDB } from "@/lib/mongodb";
import Prompt from "@/models/Prompt";

export const dynamic = "force-dynamic";

async function getPublicPrompt(id) {
  if (!mongoose.isValidObjectId(id)) return null;
  await connectDB();
  return Prompt.findOne({ _id: id, isPublic: true }).lean();
}

export async function generateMetadata({ params }) {
  const p = await getPublicPrompt(params.id);
  if (!p) return { title: "Playlist not found — SoundSage" };

  const base = process.env.NEXTAUTH_URL || "http://localhost:3000";
  const ogUrl = `${base}/api/share/${params.id}/og`;
  const title = `"${p.promptText}" — SoundSage`;
  const description = `A ${(p.recommendations || []).length}-track playlist generated by AI.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      images: [{ url: ogUrl, width: 1200, height: 630 }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogUrl],
    },
  };
}

export default async function SharePage({ params }) {
  const p = await getPublicPrompt(params.id);
  if (!p) notFound();

  const tracks = p.recommendations || [];
  const mosaicTracks = tracks.slice(0, 8);

  return (
    <main className="min-h-screen bg-neutral-950 text-white">
      {/* Header */}
      <header className="border-b border-neutral-800 px-6 py-4">
        <Link href="/" className="text-xl font-bold tracking-tight">
          Sound<span className="text-spotify">Sage</span>
        </Link>
      </header>

      <div className="max-w-2xl mx-auto px-6 py-12">
        {/* Prompt */}
        <div className="mb-8">
          <p className="text-sm text-neutral-500 uppercase tracking-wider mb-2">
            Playlist vibe
          </p>
          <h1 className="text-3xl font-bold leading-snug">
            &ldquo;{p.promptText}&rdquo;
          </h1>
          <p className="mt-2 text-sm text-neutral-500">
            {tracks.length} tracks
          </p>
        </div>

        {/* 4×2 album art mosaic */}
        {mosaicTracks.length > 0 && (
          <div className="grid grid-cols-4 gap-0.5 rounded-xl overflow-hidden mb-10 w-fit">
            {Array.from({ length: 8 }).map((_, i) => {
              const art = mosaicTracks[i]?.albumArt;
              return art ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  key={i}
                  src={art}
                  alt={mosaicTracks[i]?.title || ""}
                  width={120}
                  height={120}
                  className="w-[100px] h-[100px] sm:w-[120px] sm:h-[120px] object-cover"
                />
              ) : (
                <div
                  key={i}
                  className="w-[100px] h-[100px] sm:w-[120px] sm:h-[120px] bg-neutral-800"
                />
              );
            })}
          </div>
        )}

        {/* Track list */}
        <div className="space-y-1 mb-12">
          {tracks.map((t, i) => (
            <div
              key={t.spotifyTrackId || i}
              className="flex items-center gap-3 py-2 border-b border-neutral-800/60 last:border-0"
            >
              <span className="text-neutral-600 text-sm w-6 text-right shrink-0">
                {i + 1}
              </span>
              <div className="min-w-0">
                <p className="font-medium text-sm truncate">{t.title}</p>
                <p className="text-neutral-400 text-xs truncate">{t.artist}</p>
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="flex flex-col items-center gap-3 text-center">
          <p className="text-neutral-400 text-sm">
            Like this vibe? Build your own AI playlist.
          </p>
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-spotify hover:brightness-110 text-black font-semibold transition-colors"
          >
            Generate your own
          </Link>
        </div>
      </div>
    </main>
  );
}
