export const SAMPLE_TRACKS = [
  {
    id: "nightcall",
    title: "Nightcall",
    artist: "Kavinsky",
    album: "Nightcall",
    durationLabel: "4:18",
    albumArt: null,
    gradientFrom: "#1a1a2e",
    gradientTo: "#e94560",
  },
  {
    id: "moment-apart",
    title: "A Moment Apart",
    artist: "ODESZA",
    album: "A Moment Apart",
    durationLabel: "3:53",
    albumArt: null,
    gradientFrom: "#0f3460",
    gradientTo: "#533483",
  },
  {
    id: "less-i-know",
    title: "The Less I Know The Better",
    artist: "Tame Impala",
    album: "Currents",
    durationLabel: "3:38",
    albumArt: null,
    gradientFrom: "#e8630a",
    gradientTo: "#c23152",
  },
  {
    id: "sweater-weather",
    title: "Sweater Weather",
    artist: "The Neighbourhood",
    album: "I Love You.",
    durationLabel: "4:00",
    albumArt: null,
    gradientFrom: "#1c1c1c",
    gradientTo: "#4a4a4a",
  },
  {
    id: "lost-in-yesterday",
    title: "Lost In Yesterday",
    artist: "Tame Impala",
    album: "The Slow Rush",
    durationLabel: "4:08",
    albumArt: null,
    gradientFrom: "#ff6b35",
    gradientTo: "#f7c59f",
  },
  {
    id: "blonde",
    title: "Pink + White",
    artist: "Frank Ocean",
    album: "Blonde",
    durationLabel: "3:04",
    albumArt: null,
    gradientFrom: "#d4a5a5",
    gradientTo: "#9b5de5",
  },
];

export const DEFAULT_TRACK_ID = "less-i-know";
